spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.12.121.115:3306/sq_888xin21?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: sq_888xin21
    password: alb753
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  #提供给前端的文件访问目录
  resources:
    #    static-locations: file:G:/word/attachments,file:G:/word/send/attachments/
    static-locations: classpath:/static/

